AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS--Skill_Alexa_Com_DynamoDB_e_Python

  Sample SAM Template for Alexa Skill with DynamoDB persistence

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_PERSISTENCE_TABLE: !Ref PersistenceTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersistenceTable
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill

  PersistenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  AlexaSkillFunction:
    Description: "Alexa Skill Lambda Function ARN"
    Value: !GetAtt AlexaSkillFunction.Arn
  AlexaSkillFunctionIamRole:
    Description: "Implicit IAM Role created for Alexa Skill function"
    Value: !GetAtt AlexaSkillFunctionRole.Arn
